name: Publish
on:
  push:
    branches:
      - master

jobs:
  push_new_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install packages
        run: yarn
      - run: yarn build
      - name: Build & Deploy
        run: |
          /bin/bash .github/scripts/prepareAwsCredentials.sh
          cat ~/.aws/credentials
          yarn deploy
          rm ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
